### PR TITLE
Bump scuttlebot to 12.0.0 and use unix socket + noauth for local sbot connection

### PR DESCRIPTION
**Pull request by arj03**
Can people running npm start help test this?

Should be faster :rocket:

### CODE REVIEW

**Comment by cryptix** [comment]
Yeeey! I’d be especially interested in OSX and windows feedback.

**Comment by Happy0** [comment]
@arj03  I get:

```
unix socket client
err? Error {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/home/happy0/.ssb/socket' }
unix socket client
err? Error {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/home/happy0/.ssb/socket' }
unix socket client
err? Error {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/home/happy0/.ssb/socket' }

```

(and a red light at the top right of patchbay, and no content)

**Comment by arj03** [comment]
Thanks for testing @Happy0 

I can't reproduce this locally :( 

If I run npm start in terminal I get:

```
npm start

> patchbay@7.14.0 start /home/chrx/dev/patchbay-workie
> electron index.js -- --title patchbay

STARTING electron
STARTING SBOT
LOADING config
listening on socket unix:/home/chrx/.ssb/socket
ssb-friends: stream legacy api used
Error { notFound: true, status: 404 }
info @6CA SBOT 458 peers loaded from /home/chrx/.ssb/gossip.json 
info @6CA SBOT mle.party:282:@rwf35M6L92OXvy42sUcH+eRJkfOIrcKGwoDQopl6rxQ=.ed25519 CONNECTING 
info @6CA SBOT ssb.timjrobinson.com:8008:@yH24II8DjCgSvYRtG9C3nWXzx0mSCRNjh8DjTWyN9Mk=.ed25519 CONNECTING
LOADING config
unix socket client
STARTING app
```

Can you check if the file `/home/happy0/.ssb/socket` exists?

**Comment by christianbundy** [comment]
I'm getting the same behavior as @Happy0, although with *only* the sbot upgrade everything works fine.

I was able to confirm that Scuttlebot 12 works fine without the socket change (see `sbot-12`), but when running `npm start` it complains that `~/.ssb/socket` doesn't exist. I can confirm that the file doesn't exist. Here's a screencast verifying the behavior:

[asciicast](https://asciinema.org/a/MxjxpHimRRBGcaOZMxBO9Dr0t)

Any ideas on how to troubleshoot?

```console
$ uname -a
Linux samus 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
```

**Comment by christianbundy** [comment]
Also, would you mind adding the new `package-lock.json` to this branch? Currently this breaks `npm ci`:

```console
$ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's scuttlebot@11.4.4 does not satisfy scuttlebot@^12.0.0
npm ERR! Invalid: lock file's ssb-config@2.2.1 does not satisfy ssb-config@^2.3.0

**Comment by arj03** [comment]
Oh thanks @christianbundy. The config was not upgraded, so it's not loading the unix plugin. Will fix!

**Comment by christianbundy** [comment]
I'm sure there's a more elegant way to do this without clobbering the user defaults, but here's a minimal patch that's working for me:

```diff
diff --git a/config.js b/config.js
index eca4fb1..df13da2 100644
--- a/config.js
+++ b/config.js
@@ -16,6 +16,18 @@ exports.create = (api) => {
       console.log('LOADING config')
       config = Config(appName, opts)
       config.keys = ssbKeys.loadOrCreateSync(Path.join(config.path, 'secret'))
+      config.connections = {
+        "incoming": {
+          "unix": [{ "scope": "local", "transform": "noauth" }],
+          "net": [{
+            "port": 8008,
+            "scope": "public","transform": "shs"
+          }]
+        },
+        "outgoing": {
+          "net": [{ "transform": "shs" }],
+        }
+      }
 
       // HACK: fix offline on windows by specifying 127.0.0.1 instead of localhost (default)
       config.remote = `unix:${Path.join(config.path, 'socket')}:~noauth:${config.keys.id.slice(1).replace('.ed25519', '')}`
```

**Comment by arj03** [comment]
@christianbundy and @Happy0 can you try again? Should be fixed now :)

**Comment by christianbundy** [comment]
Done, and everything seems to be working perfectly (both the socket and `npm ci`). Thanks!

**Comment by arj03** [comment]
Looks good, thanks!

**Comment by arj03** [comment]
merged, thanks all for testing and fixing!

**Pull request merged**
