### PR TITLE
[WIP] update to ssb-server@13.5.2

### PR DESCRIPTION
**Pull request by mixmix**
I want to use `scuttle-shell`, I [couldn't get it running](https://github.com/ssbc/patchbay/pull/295) so this is an incremental step - bring the server version into alignment.

### CODE REVIEW

**Comment by mixmix** [comment]
Here are the current errors I'm hitting when I `npm start`.
I've looked through the files in the stack trace but I don't know what I'm looking for... I think the server isn't starting right and my guess is because it's not getting the config it wants?
(I also noticed ssb-client has some really old deps. Probably not related, but made a [PR](https://github.com/ssbc/ssb-client/pull/35))

```bash
TypeError: proto.server is not a function
    at Object.server (/home/mix/projects/SSBC/patchbay/node_modules/secret-stack/node_modules/multiserver/compose.js:96:29)
    at /home/mix/projects/SSBC/patchbay/node_modules/secret-stack/node_modules/multiserver/index.js:31:21
    at Array.map (<anonymous>)
    at Object.server (/home/mix/projects/SSBC/patchbay/node_modules/secret-stack/node_modules/multiserver/index.js:30:26)
    at setupMultiserver (/home/mix/projects/SSBC/patchbay/node_modules/secret-stack/index.js:173:21)
    at EventEmitter.getAddress (/home/mix/projects/SSBC/patchbay/node_modules/secret-stack/index.js:209:11)
    at EventEmitter.hooked [as getAddress] (/home/mix/projects/SSBC/patchbay/node_modules/hoox/index.js:10:15)
    at /home/mix/projects/SSBC/patchbay/node_modules/ssb-server/plugins/local.js:85:30
Error: listen EADDRINUSE 2407:7000:9c49:4e00:7cba:778b:7b7f:e6f0:8008
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by arj03** [comment]
Can you post your ~/.ssb/config?

**Comment by cryptix** [comment]
Hrm.. the `config.js` might need a `server:true` on the unix socket to get this working but I wonder how it worked before.... I'll try this later on a clean install.

related:
* https://github.com/ssbc/multiserver/issues/33
* https://github.com/ssbc/ssb-server/issues/577
* https://github.com/ssbc/multiserver/pull/34

**Comment by christianbundy** [comment]
I think the problem is happening in the config merging:

- Throws error: https://github.com/fraction/minimal-ssb-server/blob/master/index.js
- No problem: https://github.com/fraction/minimal-ssb-server/blob/working-ssb-server/index.js

([diff](https://github.com/fraction/minimal-ssb-server/compare/working-ssb-server))

**Comment by christianbundy** [comment]
Just pushed a commit adding `server: true` and it seems to be working now. Force-pushed because I'd accidentally pushed a merge commit as well.

**Comment by mixmix** [comment]
```bash
mixmix  » cat ~/.ssb/config
{
  "plugins": {
    "ssb-npm-registry": false
  }
}
```

I knew it was possible for things in here to sneak in so went and gutted it some time ago!

**Comment by mixmix** [comment]
Cool, yeah that get's me past the `server.proto` error (btw how did you figure that out @christianbundy ... did you read all the links @cryptix left?)

Now on to this error, which @arj03 says is in ssb-db : https://github.com/ssbc/patchbay/pull/295#issuecomment-451843296

```bash
EncodingError: Unexpected token % in JSON at position 0
    at /home/mix/projects/SSBC/patchbay/node_modules/level-sublevel/node_modules/levelup/lib/read-stream.js:60:28
    at /home/mix/projects/SSBC/patchbay/node_modules/ssb-db/node_modules/abstract-leveldown/abstract-iterator.js:29:14
    at /home/mix/projects/SSBC/patchbay/node_modules/ssb-db/node_modules/encoding-down/index.js:126:5
    at /home/mix/projects/SSBC/patchbay/node_modules/ssb-db/node_modules/abstract-leveldown/abstract-iterator.js:29:14
    at /home/mix/projects/SSBC/patchbay/node_modules/ssb-db/node_modules/leveldown/iterator.js:45:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by christianbundy** [comment]
@mixmix 

Yeah, I saw ssbc/ssb-server#577 describing a problem so I opened ssbc/multiserver#33 to request some documentation, and I think ssbc/multiserver#34 adds test coverage that shows that `server: true` is required now but nobody knows how to use it or why `server` must be truthy (I think it's meant to be an object (?)).

**Pull request merged**
