### PR TITLE
Support links with unbox key

### PR DESCRIPTION
**Pull request by arj03**
With this, we can now read super secret messages posted as links with an unbox key. See this message for two examples: %yTo0gv+o7dkJ0vn5K6FHh+q/6ZJbIghboSOFNlm+wLE=.sha256

### CODE REVIEW

**Comment by arj03** [comment]
It even works with backlinks, so I found this pot of gold :heart: 

%8Cma+JRgxTb0aBNvlwPpGKZUhT6avpS9xxnLu1ZoPtQ=.sha256

**Comment by arj03** [comment]
@mixmix or @christianbundy any love for this?

**Comment by christianbundy** [comment]
Sorry this review took so long!

This looks great to me, although I can only see the examples in your first comment. The second link you gave just shows up as encrypted, but I think that's because I need an unbox key. LGTM.

**Comment by arj03** [comment]
Thanks @christianbundy! No need to apologize :)

The wierd thing is that I'm quite sure this worked when I did the patch, but yeah I can see now that the links are broken, it doesn't include the ? part, so the unbox key gets lost. This linked works though:

`
%DZ16YazxNOR7Q2Eb6o6mh7F/1I5a7xmFfvEMpoLr1H8=.sha256?unbox=BrlO21y5MiViDsrlK+SH8ALmXpSOvBqC99Np45wY09/q
`

So it must be something in the markdown renderer, that you know a lot about, any idea what is going on?

**Comment by arj03** [comment]
Nevermind, links from posts works fine. Its just that the unlink part does not get included in the url

**Pull request merged**
