### PR TITLE
Saner start defaults

### PR DESCRIPTION
**Pull request by arj03**
I'm not sure if this is valuable for anyone else. But thought I would try and see, since I got a merge conflict updating my branch :-)

### CODE REVIEW

**Comment by mixmix** [comment]
hey I'm not so into the zoom here. Can you unpack what it is you want to see? 
Could be that if there's config you want to persist that this could be a good motivation for building a depject module called `patch-preferences` or something?

**Comment by arj03** [comment]
Sure. I think the title should be default. The other ones would probably be better in some kind of preferences that saves and auto-loads on start.

**Comment by arj03** [comment]
Closing this. Will do a new PR

**Comment by arj03** [comment]
@mixmix See https://github.com/ssbc/patchbay/pull/132 :)

**Pull request closed without merging**
