### PR TITLE
added display of your current funds

### PR DESCRIPTION
**Pull request by dangerousbeans**

### CODE REVIEW

**Comment by arj03** [comment]
I really like this, but without a way of added these transactions in patchbay its a somewhat half experience. @dangerousbeans are you planning on doing that as well?

**Comment by dominictarr** [comment]
@arj03 that is a good point, but on the other hand, I think our policy should be merge merge merge! if it doesn't break stuff, merge it. obviously we'll need making transactions for this part to make sense, but we can still add this. that said, if there was a way to make a transaction in the PR it would be an easier argument!

**Comment by mixmix** [comment]
I think there's a minor conflict with the ssb-chess version. I can fix that and merge this when I get up

**Comment by mixmix** [comment]
Hey I've pull this, merged master, and smoke-testing it I'm getting a bug.
I've added you as a collaborator on this repo @dangerousbeans and opened a new local PR : https://github.com/ssbc/patchbay/pull/131

**Pull request closed without merging**
