### PR TITLE
Upgrade ssb-friends

### PR DESCRIPTION
**Pull request by christianbundy**
A few more patches have landed in ssb-friends and I'm *personally* not seeing any buggy behavior. Anyone else having issues with ssb-friends@3?

---

%uWpkHb2v1fHZ4dc9p4ydIoGgUrixq/OYfrGiTVMTX4M=.sha256

### CODE REVIEW

**Comment by cryptix** [comment]
the problems I had were fixed in v3.1.2.

**Comment by cryptix** [comment]
this was handled in #845

**Comment by cryptix** [comment]
oops... that was on patch_work_..

**Comment by mixmix** [comment]
I'm gonna manually upgrade i na new commit because conflict.
Thanks for tracking this all

cc @arj03 we're trying friends@3 again. STRAP IN

**Pull request closed without merging**
