### PR TITLE
display who a profile is blocking, as well as who they are blocked by

### PR DESCRIPTION
**Pull request by dangerousbeans**
screen shot 2017-10-22 at 2 17 24 pm

### CODE REVIEW

**Comment by arj03** [comment]
@dangerousbeans I have tested this an it works great. Cool stuff! Not sure if I want it at the top above Friends. Under Followers would be better I think.

**Comment by dangerousbeans** [comment]
@arj03 I agree, though this is just adding "Blocking" beside "Blocked By" - could move both down?

**Comment by evbogue** [comment]
This is cool, and I should implement this in minbase. But it made me wonder: who is blocking me, and what did I do?

**Comment by evbogue** [comment]
But I'm in good company, because if anyone is blocking @mixmix's dad might as well block me too.

**Comment by arj03** [comment]
@dangerousbeans I think they are asymmetric. If someone is blocked I wanted to see it next to their name and picture. But if someone is blocking someone else, I don't need to see it right away. It is less important than who their friends are. I think ;)

**Comment by arj03** [comment]
Yeah @evbogue. Currently the ban is the big hammer. We need something more fine grained. Would be really nice to be able to tag posts as offence as that it probably the first step towards banning ;) This has been talked about, I think we just need someone to actually implement it :)

**Comment by evbogue** [comment]
@arj03 I think flag and downvote have both been discussed. The original Patchwork had flag for a brief moment in time, if I remember correctly.

I find myself wondering if people want their blocklists to be public on their profiles? I'm not the person in the screenshot above, but I imagine that the person in question was trying to distance themselves from me when they went from following me to blocking me. Having my profile photo on their profile page would probably lead to more questions than answers.

**Comment by evbogue** [comment]
sorry, my trackpad freaked out and hit the close button.

**Comment by arj03** [comment]
The info is public anyway. The reason why I think this is so great is that maybe you blocked somebody at one point but forgot about it and with this its really easy to see who you blocked.

**Comment by dangerousbeans** [comment]
right now the blocks are broadcast very publicly but the 'blockers' are hidden in all the UI

if you were relying on a social connection to connect you to another group, that link may be lost if someone decides to block people

Or, if a pub decides to block big ranges of people than maybe you'd want to be able to see that

Anyway I think we should merge this but also redesign the UI of the profile page

**Comment by arj03** [comment]
Sure I think this is good as well, are you okay with me moving it down a bit?

**Comment by dangerousbeans** [comment]
@arj03 yis

**Comment by mixmix** [comment]
Cool!

I started a branch somewhere to make the different relationships like tabs
you can click through. This way we can give a lot of detail without having
to jam up the whole interface.

I'm keen to get "friends in common" in here too

**Comment by dangerousbeans** [comment]
hellz yes for friends in common

**Pull request merged**
