### PR TITLE
Resolve dependencies and lint

### PR DESCRIPTION
**Pull request by christianbundy**
- delete unused dependencies
- record missing dependencies
- upgrade all the things
- cross fingers and test
- push to github
- write this list

---

I've also auto-fixed some cosmetic syntax stuff with `npm run lint -- --fix`. I've added it to this PR because this PR includes the new version of `standard`, which had slightly different results in #226.

### CODE REVIEW

**Comment by mixmix** [comment]
this looks great!
Smoke testing it now :smoking:

**Comment by arj03** [comment]
@keks has problems with ssb-friends 3, so I'd be cautious with that, other things look good.

**Comment by mixmix** [comment]
thanks for the heads up @arj03 I did note those upgrades and that they might be trouble.
I've merged this in https://github.com/ssbc/patchbay/pull/230 ... if there are any trouble you experience please feel free to roll things back @arj03 

Thanks for this contribution @christianbundy !

**Comment by alanz** [comment]
@christianbundy See %Iqz2SD9cV5weiHMc78Mx3KARp9A1VpvabH6IOdc5jNk=.sha256 on SSB

**Pull request merged**
