### PR TITLE
new icons

### PR DESCRIPTION
**Pull request by mixmix**
hermes-patchbay svg_256x256

The majesty, the ease of differentiation (finally) ! 

I whipped up the ico / icns files based on tools I could ge tto work online (https://iconverticons.com/online/ was broken :cry:). So need to test this can build working installers on windows / mac before merging this

### CODE REVIEW

**Comment by marylychee** [comment]
Looks great @mixmix !!  I mainly made this using some of the colours already in patchbay currently. 

This version is a bit more vapourwave as @pospi puts it, and is more of the actual colours

image

**Comment by marylychee** [comment]
How do I test this? I've got the branch running but it only shows the electron icon. 
image

can I only test if it's already built?

**Comment by mixmix** [comment]
yeah build it yourself, try `npm run dist` !

It will likely error for two reasons:
- can't sign it (because most people haven't bought some apple keys, I have :cry: )
- can't push it github (no GH_TOKEN set up)

the first one might be fatal.

Hey I hecking love that vapourwave version ...it's kinda surprising seeing the colours I've picked semi independantly for different parts of the app pulled out and that they all kinda work together. Nice.

Any chance you could attach that svg here ?
If you're feeling especially generous you could try making a `.ico` and `.icns` file (windows and mac icons) on https://iconverticons.com/online/ (note the icns export needs to be high res = 256x256 I think)

**Comment by marylychee** [comment]
Trying to attach it here. Having some troubles downloading it but here's the share link @mixmix 
https://iconverticons.com/icons/1559605a51cc1f3b/

**Comment by marylychee** [comment]
github doesn't let me paste SVGs as it doesn't support that file, but hopefully that link gives us what we need.

but yeah TOTALLY! I'm digging the vapourware colours too!! so fun!

**Comment by mixmix** [comment]
Arg, yeah iconverticons is giving me grief as well. I was hoping it was just my machine.
If you have the patchbay repo can you just commit the svg into this branch (in the /build folder) and push it up to this branch. That or if you're feeling patient search the web for ico and icns tools and push up the results to the repo.

**Comment by marylychee** [comment]
this is most of the work to build icn and icns, except that Mac needs larger icon files. 

Larger icon files are unnecessary and don't very solar punk vapour wave.

**Comment by marylychee** [comment]
to clarify: I searched the web for tools, and then made a builder that creates ico and icns files 

works by running `npm run icon` which will do `node build/build-icon.js`

**Pull request merged**
