### PR TITLE
Work with sbot 13.2.1

### PR DESCRIPTION
**Pull request by arj03**
Here you go @mixmix 

As cryptix pointed out, it is [this](https://github.com/ssbc/scuttlebot/issues/577) issue.

### CODE REVIEW

**Comment by christianbundy** [comment]
I'm not familiar with that config, are there any docs on this change so I can familiarize myself?

**Comment by mixmix** [comment]
Thanks for sorting that so quickly.
Im also confused as to where to find docs. I think i read them once but
they didn't really detail all the options last looked

Is it worth upgrading the installers I just made if it takes me say an
hour?

**Comment by arj03** [comment]
@christianbundy that is the whole problem. There is no documentation update for the new stuff (13.1). See the error I linked to ;-) Things should be documented in ssb-config.

Sbot 13.1 is a dominics rework of scope. 13.2 just adds the disable-links that doesn't do anything for patchbay, as it is not using that plugin anyway. And 13.2.1 is a minor bugfix for people hacking their own config and plugins.install blowing up their config. So in short, I wouldn't bother with a new installer @mixmix.

**Comment by mixmix** [comment]
Good news is ssb- config now has more docs!

**Pull request closed without merging**
