### PR TITLE
Adds dislike button as experiment

### PR DESCRIPTION
**Pull request by pietgeursen**
dislike

### CODE REVIEW

**Comment by pietgeursen** [comment]
goes with https://github.com/ssbc/patchcore/pull/15

**Comment by evbogue** [comment]
I'm all for this feature, but wasn't brave enough to implement it myself. 

I'd add a confirm dialog to dislike, so no one accidentally hits it, thus causing major drama.

**Comment by evbogue** [comment]
Also, if this feature becomes the norm, I'm happy to implement in http://github.com/evbogue/minbay

**Comment by dominictarr** [comment]
:+1: :+1: to having a confirm.

**Comment by evbogue** [comment]
We're also [talking about this issue on scuttlebot](http://viewer.scuttlebot.io/%25SPzkzorf9JMtf2sMZ2/B5l7bzgwK826xCw42TzueCEA=.sha256)

**Pull request closed without merging**
