### PR TITLE
upgrade scuttlebot + ssb-private

### PR DESCRIPTION
**Pull request by mixmix**

### CODE REVIEW

**Comment by mixmix** [comment]
hey @arj03 do you reckon this is stable enough to run in master?

If you think it is, please feel free to merge.

**Comment by arj03** [comment]
Yeah, I've been running 11.3 for a while and its really stable for me now.

**Comment by mixmix** [comment]
Woop!

There's a thing I'm watching where jumping between versions of softener
plugins sometimes breaks my indexes... Like my public feed decides to
break, or inbox won't load, but notifications will.
Only thing I can see is the counts in "sbot status" stall before getting
fully up to sync.

Anyway, just wanted to mention it in case you hit it. Wiping indexes works
fine to fix it

**Comment by arj03** [comment]
What version of secure-scuttlebutt do you have? Dominic did some fixes to the indexing in 18.0.5.

**Pull request merged**
