### PR TITLE
Fix network page with missing depject dep

### LINKED ISSUE #289: TypeError: Cannot read property 'sync' of undefined
Same as #219, but for the new `/network` page.

```
TypeError: Cannot read property 'sync' of undefined
    at HTMLAnchorElement.ev-click (/home/christianbundy/src/ssbc/patchbay/app/page/network.js:29:33)
```

### PR DESCRIPTION
**Pull request by christianbundy**
Resolves #289 

I think I'm the only one who needs this dep because others are using keyboard shortcuts that don't trigger click events.

### CODE REVIEW

**Comment by christianbundy** [comment]
Sorry @mixmix, this one may actually be worth doing a new release afterward. I thought it was just me, but it looks like Happy had the same problem. Anything I can do to help with the build/release process?

**Comment by mixmix** [comment]
nah it's not worth 30-60 mins of messing around - you're both devs, you can pull `master`!

sorry it was hasty and poorly tested.

**Comment by mixmix** [comment]
p.s. please feel free to merge obviously bugfixes to obviously stupid bugs. Make a PR and mention, then just merge :)

**Comment by christianbundy** [comment]
Works for me! I'm always on `master`, I was just thinking that this may affect non-devs but we'll cross that bridge when we get there. I'll merge trivial stuff in the future. :+1:

**Pull request merged**
