### PR TITLE
Patch book

### PR DESCRIPTION
**Pull request by arj03**
I think this is ready to go @mixmix

### CODE REVIEW

**Comment by Happy0** [comment]
\o/

**Comment by mixmix** [comment]
Awesome, I'll check it today and all going well let's merge.

Get some sweet screenshots ready to post and tweet about it - I think
celebrating and sharing progress is a good way to let people know what
we're doing and help them see how the ecosystem is progressing

**Comment by mixmix** [comment]
awesome, lets go !

I've added you as a collaborator to patchbay. If you even want to bump a version of patch-book, please feel free to do that on the master branch. Push to github and scuttlebutt repos ideally 

great work @arj03 xxx

**Comment by Happy0** [comment]
Congrats! I look forward to giving it a try :D

**Pull request merged**
