### PR TITLE
Introducing chess

### PR DESCRIPTION
**Pull request by Happy0**
Hullo!

@mixmix you still interested in integrating this into patchbay?

There's probably more that needs to be done before this pull request can be merged, but I thought I'd open it early so we can start a conversation about what needs to be done for it to be ready to be merged :)

### CODE REVIEW

**Comment by Happy0** [comment]
There's a few commits on this pull request that are just bumping the ssb-chess version in package.json.

Let me know if you'd like me to rebase to squash all these commits into one.

**Comment by mixmix** [comment]
MERGED !!!!!!

**Comment by mixmix** [comment]
Nice to see how light the pull request is with depject.

**Comment by Happy0** [comment]
Haha. Indeed. Works well :).

Would you like more improvements and functionality (there's plenty to be
done) in ssb-chess before this is merged?

Can't see whether you've said anything on the thread on scuttlebutt as the
external viewer site is down and I'm at work.

**Comment by Happy0** [comment]
Oh wait. It was merged. Awesome, thanks! :)

Look forward to doing more

**Comment by mixmix** [comment]
I think there is room for improvement for the interface, but I'm a big fan
of getting things into use and learning as you go.
I think what you've already built is really functional and awesome.

**Comment by Happy0** [comment]
Aww, thanks :D.

Cheers again for all the issues you helped me uncover by helping me test.

**Pull request merged**
